spring:
  application:
    name: book-service
  
server:
  port: 1112

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://13.126.236.39:8080/eureka}
  instance:
    prefer-ip-address: true
