spring:
  application:
    name: book-service
  
server:
  port: 1112

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://35.154.32.166:8761/eureka}
  instance:
    prefer-ip-address: true
